# Stage 1: Build
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app

# 1. Copy the Parent POM
COPY pom.xml .

# 2. Copy the api-gateway folder
COPY api-gateway/ api-gateway/

# 3. Build using the api-gateway POM file directly
RUN mvn clean package -f api-gateway/pom.xml -DskipTests

# Stage 2: Run
FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY --from=build /app/api-gateway/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]