server:
  port: 8081
  forward-headers-strategy: framework

spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:798583041423-pk0naufnng9e0de7cqrgpjskdd22h1c0.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET: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}
            scope:
              - profile
              - email
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/