server:
  port: ${SERVER_PORT}

spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: ${SPRING_APPLICATION_NAME}

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: ${JPA_SHOW_SQL}
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}