# Stage 1: Build
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app

# Copy the Parent POM
COPY pom.xml .

# FIX: Remove the <modules> section from the root pom.xml
RUN sed -i '/<modules>/,/<\/modules>/d' pom.xml

# Copy the auth-service folder
COPY auth-service/ auth-service/

# Build only the auth-service
RUN mvn clean package -pl auth-service -DskipTests

# Stage 2: Run
FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY --from=build /app/auth-service/target/*.jar app.jar

EXPOSE 8081
ENTRYPOINT ["java","-jar","app.jar"]
