# Stage 1: Build
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app

# 1. Copy the Parent POM
COPY pom.xml .

# 2. Copy the auth-service folder
COPY auth-service/ auth-service/

# 3. Build using the auth-service POM file directly
RUN mvn clean package -f auth-service/pom.xml -DskipTests

# Stage 2: Run
FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY --from=build /app/auth-service/target/*.jar app.jar

EXPOSE 8081
ENTRYPOINT ["java","-jar","app.jar"]
