# Stage 1: Build
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app

# Copy the Parent POM first
COPY pom.xml .

# Copy the qma-service folder
COPY qma-service/ qma-service/

# Build only the qma-service
RUN mvn clean package -pl qma-service -DskipTests

# Stage 2: Run
FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY --from=build /app/qma-service/target/*.jar app.jar

EXPOSE 8082
ENTRYPOINT ["java","-jar","app.jar"]
